settings:
  # A working directory.
  #
  # Used for things like cloning the destination git repo, and committing
  # changed files before pushing them back to the git remote.
  #
  # Default: ~/.clibato
  workdir: /tmp/.clibato
contents:
  .zshrc: {}
  .vimrc: {}
  todo.txt:
    source: '~/Documents/todo.txt'
destination:
  type: "repository"
  path: "git@github.com:jigarius/clibato.git"
  branch: "main"
  # The name and mail are used for 'git commit'.
  user:
    name: "Clibato"
    mail: "clibato@example.com"
