contents:
  .zshrc: {}
  .vimrc: {}
  todo.txt:
    source: '~/Documents/todo.txt'
destination:
  type: "repository"
  path: "/tmp/clibato"
  remote: "git@github.com:jigarius/clibato.git"
  branch: "main"
  # The name and mail are used for 'git commit'.
  user:
    name: "Clibato"
    mail: "clibato@example.com"
