name: Clibato
services:
  main:
    type: python
    build:
      - pip install -r requirements.txt -r requirements-dev.txt
      - chmod +x /app/main.py
      - ln -s /app/main.py /usr/local/bin/clibato
tooling:
  python:
    service: main
    cmd: python3
  lint:
    service: main
    cmd: pylint main.py clibato test
  test:
    service: main
    cmd: nosetests --rednose
