name: Clibato
services:
  main:
    type: python
    build:
      - echo "Installing dependencies..."
      - make install
      - pip install -e .
tooling:
  clibato:
    service: main
    cmd: clibato
  python:
    service: main
    cmd: python3
  lint:
    service: main
    cmd: make lint
  test:
    service: main
    cmd: make test
