name: Clibato
services:
  main:
    type: python
    build:
      - echo "Installing dependencies..."
      - make install
      - make sandbox
      - pip install -e .
    overrides:
      environment:
        TERM: xterm-256color
        PIP_USER: 'false'
tooling:
  clibato:
    service: main
  python:
    service: main
  make:
    service: main
  lint:
    service: main
    cmd: make lint
  test:
    service: main
    cmd: make test
